version: '3.8'

services:
  discord_bot:
    build: .
    container_name: dnd_discord_bot
    restart: unless-stopped
    networks:
      - dnd_shared_network # Both containers must occupy this exact network channel

networks:
  dnd_shared_network:
    external: true
